/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tipo de actividad en el sistema
 * @export
 */
export const ActivityType = {
    Enrollment: 'enrollment',
    Question: 'question',
    Review: 'review'
} as const;
export type ActivityType = typeof ActivityType[keyof typeof ActivityType];


export function instanceOfActivityType(value: any): boolean {
    for (const key in ActivityType) {
        if (Object.prototype.hasOwnProperty.call(ActivityType, key)) {
            if (ActivityType[key as keyof typeof ActivityType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ActivityTypeFromJSON(json: any): ActivityType {
    return ActivityTypeFromJSONTyped(json, false);
}

export function ActivityTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityType {
    return json as ActivityType;
}

export function ActivityTypeToJSON(value?: ActivityType | null): any {
    return value as any;
}

export function ActivityTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ActivityType {
    return value as ActivityType;
}

