/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityType } from './ActivityType';
import {
    ActivityTypeFromJSON,
    ActivityTypeFromJSONTyped,
    ActivityTypeToJSON,
    ActivityTypeToJSONTyped,
} from './ActivityType';

/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * Identificador de la actividad
     * @type {string}
     * @memberof Activity
     */
    id: string;
    /**
     * Usuario que realizó la actividad
     * @type {string}
     * @memberof Activity
     */
    user: string;
    /**
     * Descripción de la acción
     * @type {string}
     * @memberof Activity
     */
    action: string;
    /**
     * Objetivo de la acción
     * @type {string}
     * @memberof Activity
     */
    target: string;
    /**
     * Momento de la actividad
     * @type {Date}
     * @memberof Activity
     */
    time: Date;
    /**
     * 
     * @type {ActivityType}
     * @memberof Activity
     */
    type: ActivityType;
}



/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value: object): value is Activity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ActivityFromJSON(json: any): Activity {
    return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user': json['user'],
        'action': json['action'],
        'target': json['target'],
        'time': (new Date(json['time'])),
        'type': ActivityTypeFromJSON(json['type']),
    };
}

export function ActivityToJSON(json: any): Activity {
    return ActivityToJSONTyped(json, false);
}

export function ActivityToJSONTyped(value?: Activity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user': value['user'],
        'action': value['action'],
        'target': value['target'],
        'time': value['time'].toISOString(),
        'type': ActivityTypeToJSON(value['type']),
    };
}

