/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminUsersIdStatusPatchRequest
 */
export interface AdminUsersIdStatusPatchRequest {
    /**
     * Nuevo estado (true = activo, false = inactivo/baja lógica)
     * @type {boolean}
     * @memberof AdminUsersIdStatusPatchRequest
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the AdminUsersIdStatusPatchRequest interface.
 */
export function instanceOfAdminUsersIdStatusPatchRequest(value: object): value is AdminUsersIdStatusPatchRequest {
    return true;
}

export function AdminUsersIdStatusPatchRequestFromJSON(json: any): AdminUsersIdStatusPatchRequest {
    return AdminUsersIdStatusPatchRequestFromJSONTyped(json, false);
}

export function AdminUsersIdStatusPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUsersIdStatusPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function AdminUsersIdStatusPatchRequestToJSON(json: any): AdminUsersIdStatusPatchRequest {
    return AdminUsersIdStatusPatchRequestToJSONTyped(json, false);
}

export function AdminUsersIdStatusPatchRequestToJSONTyped(value?: AdminUsersIdStatusPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isActive': value['isActive'],
    };
}

