/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsSummary
 */
export interface AnalyticsSummary {
    /**
     * Ingresos totales
     * @type {number}
     * @memberof AnalyticsSummary
     */
    totalRevenue?: number;
    /**
     * Total de estudiantes
     * @type {number}
     * @memberof AnalyticsSummary
     */
    totalStudents?: number;
    /**
     * Calificación promedio
     * @type {number}
     * @memberof AnalyticsSummary
     */
    averageRating?: number;
    /**
     * Cursos activos
     * @type {number}
     * @memberof AnalyticsSummary
     */
    activeCourses?: number;
}

/**
 * Check if a given object implements the AnalyticsSummary interface.
 */
export function instanceOfAnalyticsSummary(value: object): value is AnalyticsSummary {
    return true;
}

export function AnalyticsSummaryFromJSON(json: any): AnalyticsSummary {
    return AnalyticsSummaryFromJSONTyped(json, false);
}

export function AnalyticsSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'totalRevenue': json['totalRevenue'] == null ? undefined : json['totalRevenue'],
        'totalStudents': json['totalStudents'] == null ? undefined : json['totalStudents'],
        'averageRating': json['averageRating'] == null ? undefined : json['averageRating'],
        'activeCourses': json['activeCourses'] == null ? undefined : json['activeCourses'],
    };
}

export function AnalyticsSummaryToJSON(json: any): AnalyticsSummary {
    return AnalyticsSummaryToJSONTyped(json, false);
}

export function AnalyticsSummaryToJSONTyped(value?: AnalyticsSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalRevenue': value['totalRevenue'],
        'totalStudents': value['totalStudents'],
        'averageRating': value['averageRating'],
        'activeCourses': value['activeCourses'],
    };
}

