/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Estado de autenticación del usuario
 * @export
 */
export const AuthStatus = {
    Checking: 'checking',
    Authenticated: 'authenticated',
    NotAuthenticated: 'notAuthenticated'
} as const;
export type AuthStatus = typeof AuthStatus[keyof typeof AuthStatus];


export function instanceOfAuthStatus(value: any): boolean {
    for (const key in AuthStatus) {
        if (Object.prototype.hasOwnProperty.call(AuthStatus, key)) {
            if (AuthStatus[key as keyof typeof AuthStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AuthStatusFromJSON(json: any): AuthStatus {
    return AuthStatusFromJSONTyped(json, false);
}

export function AuthStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthStatus {
    return json as AuthStatus;
}

export function AuthStatusToJSON(value?: AuthStatus | null): any {
    return value as any;
}

export function AuthStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AuthStatus {
    return value as AuthStatus;
}

