/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseStatus } from './CourseStatus';
import {
    CourseStatusFromJSON,
    CourseStatusFromJSONTyped,
    CourseStatusToJSON,
    CourseStatusToJSONTyped,
} from './CourseStatus';

/**
 * 
 * @export
 * @interface CoursePerformance
 */
export interface CoursePerformance {
    /**
     * ID del curso
     * @type {string}
     * @memberof CoursePerformance
     */
    courseId?: string;
    /**
     * Nombre del curso
     * @type {string}
     * @memberof CoursePerformance
     */
    courseName?: string;
    /**
     * Número de estudiantes
     * @type {number}
     * @memberof CoursePerformance
     */
    students?: number;
    /**
     * Ingresos generados
     * @type {number}
     * @memberof CoursePerformance
     */
    revenue?: number;
    /**
     * Calificación del curso
     * @type {number}
     * @memberof CoursePerformance
     */
    rating?: number;
    /**
     * 
     * @type {CourseStatus}
     * @memberof CoursePerformance
     */
    status?: CourseStatus;
}



/**
 * Check if a given object implements the CoursePerformance interface.
 */
export function instanceOfCoursePerformance(value: object): value is CoursePerformance {
    return true;
}

export function CoursePerformanceFromJSON(json: any): CoursePerformance {
    return CoursePerformanceFromJSONTyped(json, false);
}

export function CoursePerformanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoursePerformance {
    if (json == null) {
        return json;
    }
    return {
        
        'courseId': json['courseId'] == null ? undefined : json['courseId'],
        'courseName': json['courseName'] == null ? undefined : json['courseName'],
        'students': json['students'] == null ? undefined : json['students'],
        'revenue': json['revenue'] == null ? undefined : json['revenue'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'status': json['status'] == null ? undefined : CourseStatusFromJSON(json['status']),
    };
}

export function CoursePerformanceToJSON(json: any): CoursePerformance {
    return CoursePerformanceToJSONTyped(json, false);
}

export function CoursePerformanceToJSONTyped(value?: CoursePerformance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courseId': value['courseId'],
        'courseName': value['courseName'],
        'students': value['students'],
        'revenue': value['revenue'],
        'rating': value['rating'],
        'status': CourseStatusToJSON(value['status']),
    };
}

