/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Estado de publicación del curso
 * @export
 */
export const CourseStatus = {
    Publicado: 'Publicado',
    Borrador: 'Borrador',
    EnRevision: 'En Revision'
} as const;
export type CourseStatus = typeof CourseStatus[keyof typeof CourseStatus];


export function instanceOfCourseStatus(value: any): boolean {
    for (const key in CourseStatus) {
        if (Object.prototype.hasOwnProperty.call(CourseStatus, key)) {
            if (CourseStatus[key as keyof typeof CourseStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CourseStatusFromJSON(json: any): CourseStatus {
    return CourseStatusFromJSONTyped(json, false);
}

export function CourseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseStatus {
    return json as CourseStatus;
}

export function CourseStatusToJSON(value?: CourseStatus | null): any {
    return value as any;
}

export function CourseStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): CourseStatus {
    return value as CourseStatus;
}

