/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Nivel de dificultad del curso
 * @export
 */
export const CourseLevel = {
    Principiante: 'Principiante',
    Intermedio: 'Intermedio',
    Avanzado: 'Avanzado'
} as const;
export type CourseLevel = typeof CourseLevel[keyof typeof CourseLevel];


export function instanceOfCourseLevel(value: any): boolean {
    for (const key in CourseLevel) {
        if (Object.prototype.hasOwnProperty.call(CourseLevel, key)) {
            if (CourseLevel[key as keyof typeof CourseLevel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CourseLevelFromJSON(json: any): CourseLevel {
    return CourseLevelFromJSONTyped(json, false);
}

export function CourseLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseLevel {
    return json as CourseLevel;
}

export function CourseLevelToJSON(value?: CourseLevel | null): any {
    return value as any;
}

export function CourseLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): CourseLevel {
    return value as CourseLevel;
}

