/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Instructor } from './Instructor';
import {
    InstructorFromJSON,
    InstructorFromJSONTyped,
    InstructorToJSON,
    InstructorToJSONTyped,
} from './Instructor';
import type { Syllabus } from './Syllabus';
import {
    SyllabusFromJSON,
    SyllabusFromJSONTyped,
    SyllabusToJSON,
    SyllabusToJSONTyped,
} from './Syllabus';
import type { CourseStatus } from './CourseStatus';
import {
    CourseStatusFromJSON,
    CourseStatusFromJSONTyped,
    CourseStatusToJSON,
    CourseStatusToJSONTyped,
} from './CourseStatus';
import type { CourseLevel } from './CourseLevel';
import {
    CourseLevelFromJSON,
    CourseLevelFromJSONTyped,
    CourseLevelToJSON,
    CourseLevelToJSONTyped,
} from './CourseLevel';

/**
 * 
 * @export
 * @interface Course
 */
export interface Course {
    /**
     * Identificador único del curso
     * @type {string}
     * @memberof Course
     */
    id?: string;
    /**
     * Nombre del curso
     * @type {string}
     * @memberof Course
     */
    name: string;
    /**
     * Descripción del curso
     * @type {string}
     * @memberof Course
     */
    description?: string;
    /**
     * URL de la imagen del curso
     * @type {string}
     * @memberof Course
     */
    imageUrl?: string;
    /**
     * Categoría del curso (ej. DISEÑO WEB, DESARROLLO, ARQUITECTURA, MARKETING)
     * @type {string}
     * @memberof Course
     */
    category: string;
    /**
     * 
     * @type {CourseLevel}
     * @memberof Course
     */
    level?: CourseLevel;
    /**
     * Precio del curso
     * @type {number}
     * @memberof Course
     */
    price: number;
    /**
     * Duración total en horas
     * @type {number}
     * @memberof Course
     */
    duration?: number;
    /**
     * Fecha de inicio del curso
     * @type {Date}
     * @memberof Course
     */
    startDate?: Date;
    /**
     * Fecha de finalización del curso
     * @type {Date}
     * @memberof Course
     */
    endDate?: Date;
    /**
     * 
     * @type {CourseStatus}
     * @memberof Course
     */
    publicationStatus: CourseStatus;
    /**
     * Fecha de creación del curso
     * @type {Date}
     * @memberof Course
     */
    createdAt?: Date;
    /**
     * Fecha de última actualización
     * @type {Date}
     * @memberof Course
     */
    updatedAt?: Date;
    /**
     * Fecha de eliminación (soft delete)
     * @type {Date}
     * @memberof Course
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {Instructor}
     * @memberof Course
     */
    instructor?: Instructor;
    /**
     * Temario del curso
     * @type {Array<Syllabus>}
     * @memberof Course
     */
    syllabus?: Array<Syllabus>;
    /**
     * Número de estudiantes inscritos
     * @type {number}
     * @memberof Course
     */
    enrolledCount?: number;
    /**
     * Versión de control de concurrencia
     * @type {number}
     * @memberof Course
     */
    version?: number;
}



/**
 * Check if a given object implements the Course interface.
 */
export function instanceOfCourse(value: object): value is Course {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('publicationStatus' in value) || value['publicationStatus'] === undefined) return false;
    return true;
}

export function CourseFromJSON(json: any): Course {
    return CourseFromJSONTyped(json, false);
}

export function CourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Course {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'category': json['category'],
        'level': json['level'] == null ? undefined : CourseLevelFromJSON(json['level']),
        'price': json['price'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'publicationStatus': CourseStatusFromJSON(json['publicationStatus']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'instructor': json['instructor'] == null ? undefined : InstructorFromJSON(json['instructor']),
        'syllabus': json['syllabus'] == null ? undefined : ((json['syllabus'] as Array<any>).map(SyllabusFromJSON)),
        'enrolledCount': json['enrolledCount'] == null ? undefined : json['enrolledCount'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function CourseToJSON(json: any): Course {
    return CourseToJSONTyped(json, false);
}

export function CourseToJSONTyped(value?: Course | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'imageUrl': value['imageUrl'],
        'category': value['category'],
        'level': CourseLevelToJSON(value['level']),
        'price': value['price'],
        'duration': value['duration'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'publicationStatus': CourseStatusToJSON(value['publicationStatus']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'deletedAt': value['deletedAt'] == null ? value['deletedAt'] : value['deletedAt'].toISOString(),
        'instructor': InstructorToJSON(value['instructor']),
        'syllabus': value['syllabus'] == null ? undefined : ((value['syllabus'] as Array<any>).map(SyllabusToJSON)),
        'enrolledCount': value['enrolledCount'],
        'version': value['version'],
    };
}

