/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DashboardStats
 */
export interface DashboardStats {
    /**
     * Total de estudiantes
     * @type {number}
     * @memberof DashboardStats
     */
    totalStudents?: number;
    /**
     * Cursos activos
     * @type {number}
     * @memberof DashboardStats
     */
    activeCourses?: number;
    /**
     * Calificación promedio
     * @type {number}
     * @memberof DashboardStats
     */
    averageRating?: number;
    /**
     * Ingresos mensuales
     * @type {number}
     * @memberof DashboardStats
     */
    monthlyRevenue?: number;
    /**
     * Crecimiento de estudiantes (%)
     * @type {number}
     * @memberof DashboardStats
     */
    studentsGrowth?: number;
    /**
     * Crecimiento de ingresos (%)
     * @type {number}
     * @memberof DashboardStats
     */
    revenueGrowth?: number;
}

/**
 * Check if a given object implements the DashboardStats interface.
 */
export function instanceOfDashboardStats(value: object): value is DashboardStats {
    return true;
}

export function DashboardStatsFromJSON(json: any): DashboardStats {
    return DashboardStatsFromJSONTyped(json, false);
}

export function DashboardStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardStats {
    if (json == null) {
        return json;
    }
    return {
        
        'totalStudents': json['totalStudents'] == null ? undefined : json['totalStudents'],
        'activeCourses': json['activeCourses'] == null ? undefined : json['activeCourses'],
        'averageRating': json['averageRating'] == null ? undefined : json['averageRating'],
        'monthlyRevenue': json['monthlyRevenue'] == null ? undefined : json['monthlyRevenue'],
        'studentsGrowth': json['studentsGrowth'] == null ? undefined : json['studentsGrowth'],
        'revenueGrowth': json['revenueGrowth'] == null ? undefined : json['revenueGrowth'],
    };
}

export function DashboardStatsToJSON(json: any): DashboardStats {
    return DashboardStatsToJSONTyped(json, false);
}

export function DashboardStatsToJSONTyped(value?: DashboardStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalStudents': value['totalStudents'],
        'activeCourses': value['activeCourses'],
        'averageRating': value['averageRating'],
        'monthlyRevenue': value['monthlyRevenue'],
        'studentsGrowth': value['studentsGrowth'],
        'revenueGrowth': value['revenueGrowth'],
    };
}

