/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Estado de inscripción del estudiante en un curso
 * @export
 */
export const EnrollmentStatus = {
    Active: 'active',
    Completed: 'completed',
    Archived: 'archived',
    NotStarted: 'not_started'
} as const;
export type EnrollmentStatus = typeof EnrollmentStatus[keyof typeof EnrollmentStatus];


export function instanceOfEnrollmentStatus(value: any): boolean {
    for (const key in EnrollmentStatus) {
        if (Object.prototype.hasOwnProperty.call(EnrollmentStatus, key)) {
            if (EnrollmentStatus[key as keyof typeof EnrollmentStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EnrollmentStatusFromJSON(json: any): EnrollmentStatus {
    return EnrollmentStatusFromJSONTyped(json, false);
}

export function EnrollmentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrollmentStatus {
    return json as EnrollmentStatus;
}

export function EnrollmentStatusToJSON(value?: EnrollmentStatus | null): any {
    return value as any;
}

export function EnrollmentStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): EnrollmentStatus {
    return value as EnrollmentStatus;
}

