/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Instructor
 */
export interface Instructor {
    /**
     * Identificador único del instructor
     * @type {string}
     * @memberof Instructor
     */
    id: string;
    /**
     * Nombre completo del instructor
     * @type {string}
     * @memberof Instructor
     */
    name: string;
    /**
     * Rol o título del instructor
     * @type {string}
     * @memberof Instructor
     */
    role: string;
    /**
     * URL del avatar del instructor
     * @type {string}
     * @memberof Instructor
     */
    avatarUrl?: string;
    /**
     * Biografía del instructor
     * @type {string}
     * @memberof Instructor
     */
    bio?: string;
}

/**
 * Check if a given object implements the Instructor interface.
 */
export function instanceOfInstructor(value: object): value is Instructor {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function InstructorFromJSON(json: any): Instructor {
    return InstructorFromJSONTyped(json, false);
}

export function InstructorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Instructor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'role': json['role'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'bio': json['bio'] == null ? undefined : json['bio'],
    };
}

export function InstructorToJSON(json: any): Instructor {
    return InstructorToJSONTyped(json, false);
}

export function InstructorToJSONTyped(value?: Instructor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'role': value['role'],
        'avatarUrl': value['avatarUrl'],
        'bio': value['bio'],
    };
}

