/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationType } from './NotificationType';
import {
    NotificationTypeFromJSON,
    NotificationTypeFromJSONTyped,
    NotificationTypeToJSON,
    NotificationTypeToJSONTyped,
} from './NotificationType';

/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * Identificador único de la notificación
     * @type {string}
     * @memberof Notification
     */
    id: string;
    /**
     * ID del usuario destinatario
     * @type {string}
     * @memberof Notification
     */
    userId: string;
    /**
     * Título de la notificación
     * @type {string}
     * @memberof Notification
     */
    title: string;
    /**
     * Mensaje de la notificación
     * @type {string}
     * @memberof Notification
     */
    message: string;
    /**
     * Fecha de la notificación
     * @type {Date}
     * @memberof Notification
     */
    date: Date;
    /**
     * Indica si la notificación ha sido leída
     * @type {boolean}
     * @memberof Notification
     */
    read: boolean;
    /**
     * 
     * @type {NotificationType}
     * @memberof Notification
     */
    type: NotificationType;
    /**
     * Enlace opcional a un recurso relacionado
     * @type {string}
     * @memberof Notification
     */
    link?: string;
}



/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('read' in value) || value['read'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'title': json['title'],
        'message': json['message'],
        'date': (new Date(json['date'])),
        'read': json['read'],
        'type': NotificationTypeFromJSON(json['type']),
        'link': json['link'] == null ? undefined : json['link'],
    };
}

export function NotificationToJSON(json: any): Notification {
    return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(value?: Notification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'title': value['title'],
        'message': value['message'],
        'date': value['date'].toISOString(),
        'read': value['read'],
        'type': NotificationTypeToJSON(value['type']),
        'link': value['link'],
    };
}

