/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevenueData
 */
export interface RevenueData {
    /**
     * Mes
     * @type {string}
     * @memberof RevenueData
     */
    month?: string;
    /**
     * Ingresos del mes
     * @type {number}
     * @memberof RevenueData
     */
    revenue?: number;
    /**
     * Inscripciones del mes
     * @type {number}
     * @memberof RevenueData
     */
    enrollments?: number;
}

/**
 * Check if a given object implements the RevenueData interface.
 */
export function instanceOfRevenueData(value: object): value is RevenueData {
    return true;
}

export function RevenueDataFromJSON(json: any): RevenueData {
    return RevenueDataFromJSONTyped(json, false);
}

export function RevenueDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevenueData {
    if (json == null) {
        return json;
    }
    return {
        
        'month': json['month'] == null ? undefined : json['month'],
        'revenue': json['revenue'] == null ? undefined : json['revenue'],
        'enrollments': json['enrollments'] == null ? undefined : json['enrollments'],
    };
}

export function RevenueDataToJSON(json: any): RevenueData {
    return RevenueDataToJSONTyped(json, false);
}

export function RevenueDataToJSONTyped(value?: RevenueData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'month': value['month'],
        'revenue': value['revenue'],
        'enrollments': value['enrollments'],
    };
}

