/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Review
 */
export interface Review {
    /**
     * Identificador único de la reseña
     * @type {string}
     * @memberof Review
     */
    id: string;
    /**
     * ID del curso valorado
     * @type {string}
     * @memberof Review
     */
    courseId: string;
    /**
     * Nombre del curso valorado
     * @type {string}
     * @memberof Review
     */
    courseName?: string;
    /**
     * ID del estudiante que valora
     * @type {string}
     * @memberof Review
     */
    studentId?: string;
    /**
     * Nombre del estudiante que valora
     * @type {string}
     * @memberof Review
     */
    studentName?: string;
    /**
     * Calificación (1-5)
     * @type {number}
     * @memberof Review
     */
    rating: number;
    /**
     * Comentario de la reseña
     * @type {string}
     * @memberof Review
     */
    comment: string;
    /**
     * Fecha de creación
     * @type {Date}
     * @memberof Review
     */
    createdAt: Date;
    /**
     * Versión de control de concurrencia
     * @type {number}
     * @memberof Review
     */
    version?: number;
}

/**
 * Check if a given object implements the Review interface.
 */
export function instanceOfReview(value: object): value is Review {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ReviewFromJSON(json: any): Review {
    return ReviewFromJSONTyped(json, false);
}

export function ReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Review {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'courseId': json['courseId'],
        'courseName': json['courseName'] == null ? undefined : json['courseName'],
        'studentId': json['studentId'] == null ? undefined : json['studentId'],
        'studentName': json['studentName'] == null ? undefined : json['studentName'],
        'rating': json['rating'],
        'comment': json['comment'],
        'createdAt': (new Date(json['createdAt'])),
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function ReviewToJSON(json: any): Review {
    return ReviewToJSONTyped(json, false);
}

export function ReviewToJSONTyped(value?: Review | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'courseId': value['courseId'],
        'courseName': value['courseName'],
        'studentId': value['studentId'],
        'studentName': value['studentName'],
        'rating': value['rating'],
        'comment': value['comment'],
        'createdAt': value['createdAt'].toISOString(),
        'version': value['version'],
    };
}

