/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentStats
 */
export interface StudentStats {
    /**
     * Número de cursos activos
     * @type {number}
     * @memberof StudentStats
     */
    activeCoursesCount?: number;
    /**
     * Número de cursos completados
     * @type {number}
     * @memberof StudentStats
     */
    completedCoursesCount?: number;
    /**
     * Número de certificados obtenidos
     * @type {number}
     * @memberof StudentStats
     */
    certificatesEarned?: number;
    /**
     * Total de horas de aprendizaje
     * @type {number}
     * @memberof StudentStats
     */
    totalHoursLearning?: number;
    /**
     * Puntuación promedio
     * @type {number}
     * @memberof StudentStats
     */
    averageScore?: number;
    /**
     * Días consecutivos de aprendizaje
     * @type {number}
     * @memberof StudentStats
     */
    learningStreakDays?: number;
}

/**
 * Check if a given object implements the StudentStats interface.
 */
export function instanceOfStudentStats(value: object): value is StudentStats {
    return true;
}

export function StudentStatsFromJSON(json: any): StudentStats {
    return StudentStatsFromJSONTyped(json, false);
}

export function StudentStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentStats {
    if (json == null) {
        return json;
    }
    return {
        
        'activeCoursesCount': json['activeCoursesCount'] == null ? undefined : json['activeCoursesCount'],
        'completedCoursesCount': json['completedCoursesCount'] == null ? undefined : json['completedCoursesCount'],
        'certificatesEarned': json['certificatesEarned'] == null ? undefined : json['certificatesEarned'],
        'totalHoursLearning': json['totalHoursLearning'] == null ? undefined : json['totalHoursLearning'],
        'averageScore': json['averageScore'] == null ? undefined : json['averageScore'],
        'learningStreakDays': json['learningStreakDays'] == null ? undefined : json['learningStreakDays'],
    };
}

export function StudentStatsToJSON(json: any): StudentStats {
    return StudentStatsToJSONTyped(json, false);
}

export function StudentStatsToJSONTyped(value?: StudentStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activeCoursesCount': value['activeCoursesCount'],
        'completedCoursesCount': value['completedCoursesCount'],
        'certificatesEarned': value['certificatesEarned'],
        'totalHoursLearning': value['totalHoursLearning'],
        'averageScore': value['averageScore'],
        'learningStreakDays': value['learningStreakDays'],
    };
}

