/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Topic } from './Topic';
import {
    TopicFromJSON,
    TopicFromJSONTyped,
    TopicToJSON,
    TopicToJSONTyped,
} from './Topic';

/**
 * 
 * @export
 * @interface Syllabus
 */
export interface Syllabus {
    /**
     * Identificador único del módulo
     * @type {string}
     * @memberof Syllabus
     */
    id?: string;
    /**
     * Título del módulo
     * @type {string}
     * @memberof Syllabus
     */
    title: string;
    /**
     * Descripción del módulo
     * @type {string}
     * @memberof Syllabus
     */
    description: string;
    /**
     * Lista de temas del módulo
     * @type {Array<Topic>}
     * @memberof Syllabus
     */
    topics: Array<Topic>;
}

/**
 * Check if a given object implements the Syllabus interface.
 */
export function instanceOfSyllabus(value: object): value is Syllabus {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('topics' in value) || value['topics'] === undefined) return false;
    return true;
}

export function SyllabusFromJSON(json: any): Syllabus {
    return SyllabusFromJSONTyped(json, false);
}

export function SyllabusFromJSONTyped(json: any, ignoreDiscriminator: boolean): Syllabus {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'description': json['description'],
        'topics': ((json['topics'] as Array<any>).map(TopicFromJSON)),
    };
}

export function SyllabusToJSON(json: any): Syllabus {
    return SyllabusToJSONTyped(json, false);
}

export function SyllabusToJSONTyped(value?: Syllabus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'topics': ((value['topics'] as Array<any>).map(TopicToJSON)),
    };
}

