/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
    /**
     * Nombre completo del usuario
     * @type {string}
     * @memberof UpdateUserRequest
     */
    name?: string;
    /**
     * Correo electrónico
     * @type {string}
     * @memberof UpdateUserRequest
     */
    email?: string;
    /**
     * URL del avatar
     * @type {string}
     * @memberof UpdateUserRequest
     */
    avatar?: string;
    /**
     * Biografía (opcional, para profesores)
     * @type {string}
     * @memberof UpdateUserRequest
     */
    bio?: string;
    /**
     * Nueva contraseña (opcional)
     * @type {string}
     * @memberof UpdateUserRequest
     */
    password?: string;
    /**
     * Versión de control de concurrencia
     * @type {number}
     * @memberof UpdateUserRequest
     */
    version?: number;
}

/**
 * Check if a given object implements the UpdateUserRequest interface.
 */
export function instanceOfUpdateUserRequest(value: object): value is UpdateUserRequest {
    return true;
}

export function UpdateUserRequestFromJSON(json: any): UpdateUserRequest {
    return UpdateUserRequestFromJSONTyped(json, false);
}

export function UpdateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'password': json['password'] == null ? undefined : json['password'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function UpdateUserRequestToJSON(json: any): UpdateUserRequest {
    return UpdateUserRequestToJSONTyped(json, false);
}

export function UpdateUserRequestToJSONTyped(value?: UpdateUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'avatar': value['avatar'],
        'bio': value['bio'],
        'password': value['password'],
        'version': value['version'],
    };
}

