/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
    RoleToJSONTyped,
} from './Role';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * Identificador único del usuario
     * @type {string}
     * @memberof User
     */
    id: string;
    /**
     * Nombre completo del usuario
     * @type {string}
     * @memberof User
     */
    name: string;
    /**
     * Correo electrónico del usuario
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * Indica si el usuario está activo (Baja lógica si es false)
     * @type {boolean}
     * @memberof User
     */
    isActive: boolean;
    /**
     * 
     * @type {Role}
     * @memberof User
     */
    role: Role;
    /**
     * URL del avatar del usuario
     * @type {string}
     * @memberof User
     */
    avatar?: string;
    /**
     * Fecha de registro del usuario
     * @type {Date}
     * @memberof User
     */
    joinDate?: Date;
    /**
     * Biografía del usuario (opcional)
     * @type {string}
     * @memberof User
     */
    bio?: string;
    /**
     * Versión de control de concurrencia
     * @type {number}
     * @memberof User
     */
    version: number;
}



/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'email': json['email'],
        'isActive': json['isActive'],
        'role': RoleFromJSON(json['role']),
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'joinDate': json['joinDate'] == null ? undefined : (new Date(json['joinDate'])),
        'bio': json['bio'] == null ? undefined : json['bio'],
        'version': json['version'],
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'isActive': value['isActive'],
        'role': RoleToJSON(value['role']),
        'avatar': value['avatar'],
        'joinDate': value['joinDate'] == null ? value['joinDate'] : value['joinDate'].toISOString(),
        'bio': value['bio'],
        'version': value['version'],
    };
}

