/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminUsersIdStatusPatchRequest,
  ErrorResponse,
  Role,
  User,
} from '../models/index';
import {
    AdminUsersIdStatusPatchRequestFromJSON,
    AdminUsersIdStatusPatchRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    RoleFromJSON,
    RoleToJSON,
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface AdminUsersGetRequest {
    role?: Role;
    isActive?: boolean;
}

export interface AdminUsersIdGetRequest {
    id: string;
}

export interface AdminUsersIdPutRequest {
    id: string;
    user: User;
}

export interface AdminUsersIdStatusPatchOperationRequest {
    id: string;
    adminUsersIdStatusPatchRequest: AdminUsersIdStatusPatchRequest;
}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     * Creates request options for adminUsersGet without sending the request
     */
    async adminUsersGetRequestOpts(requestParameters: AdminUsersGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['role'] != null) {
            queryParameters['role'] = requestParameters['role'];
        }

        if (requestParameters['isActive'] != null) {
            queryParameters['isActive'] = requestParameters['isActive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/users`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener lista paginada de usuarios (Solo ADMIN)
     * Listar todos los usuarios
     */
    async adminUsersGetRaw(requestParameters: AdminUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<User>>> {
        const requestOptions = await this.adminUsersGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserFromJSON));
    }

    /**
     * Obtener lista paginada de usuarios (Solo ADMIN)
     * Listar todos los usuarios
     */
    async adminUsersGet(requestParameters: AdminUsersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<User>> {
        const response = await this.adminUsersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminUsersIdGet without sending the request
     */
    async adminUsersIdGetRequestOpts(requestParameters: AdminUsersIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adminUsersIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener información completa de cualquier usuario por ID
     * Obtener detalles de usuario (Admin)
     */
    async adminUsersIdGetRaw(requestParameters: AdminUsersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.adminUsersIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Obtener información completa de cualquier usuario por ID
     * Obtener detalles de usuario (Admin)
     */
    async adminUsersIdGet(requestParameters: AdminUsersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.adminUsersIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminUsersIdPut without sending the request
     */
    async adminUsersIdPutRequestOpts(requestParameters: AdminUsersIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adminUsersIdPut().'
            );
        }

        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling adminUsersIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserToJSON(requestParameters['user']),
        };
    }

    /**
     * Modificar datos de cualquier usuario (incluyendo rol)
     * Modificar usuario (Admin)
     */
    async adminUsersIdPutRaw(requestParameters: AdminUsersIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.adminUsersIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Modificar datos de cualquier usuario (incluyendo rol)
     * Modificar usuario (Admin)
     */
    async adminUsersIdPut(requestParameters: AdminUsersIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.adminUsersIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminUsersIdStatusPatch without sending the request
     */
    async adminUsersIdStatusPatchRequestOpts(requestParameters: AdminUsersIdStatusPatchOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adminUsersIdStatusPatch().'
            );
        }

        if (requestParameters['adminUsersIdStatusPatchRequest'] == null) {
            throw new runtime.RequiredError(
                'adminUsersIdStatusPatchRequest',
                'Required parameter "adminUsersIdStatusPatchRequest" was null or undefined when calling adminUsersIdStatusPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/users/{id}/status`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AdminUsersIdStatusPatchRequestToJSON(requestParameters['adminUsersIdStatusPatchRequest']),
        };
    }

    /**
     * Activar o desactivar un usuario sin eliminarlo de la base de datos
     * Cambiar estado de usuario (Alta/Baja Lógica)
     */
    async adminUsersIdStatusPatchRaw(requestParameters: AdminUsersIdStatusPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.adminUsersIdStatusPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Activar o desactivar un usuario sin eliminarlo de la base de datos
     * Cambiar estado de usuario (Alta/Baja Lógica)
     */
    async adminUsersIdStatusPatch(requestParameters: AdminUsersIdStatusPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.adminUsersIdStatusPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
