/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Course,
  CourseLevel,
  CourseStatus,
  ErrorResponse,
  Syllabus,
} from '../models/index';
import {
    CourseFromJSON,
    CourseToJSON,
    CourseLevelFromJSON,
    CourseLevelToJSON,
    CourseStatusFromJSON,
    CourseStatusToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    SyllabusFromJSON,
    SyllabusToJSON,
} from '../models/index';

export interface CoursesGetRequest {
    category?: string;
    level?: CourseLevel;
    status?: CourseStatus;
}

export interface CoursesIdDeleteRequest {
    id: string;
}

export interface CoursesIdGetRequest {
    id: string;
}

export interface CoursesIdPutRequest {
    id: string;
    course: Course;
}

export interface CoursesIdSyllabusGetRequest {
    id: string;
}

export interface CoursesPostRequest {
    course: Course;
}

/**
 * 
 */
export class CursosApi extends runtime.BaseAPI {

    /**
     * Creates request options for coursesGet without sending the request
     */
    async coursesGetRequestOpts(requestParameters: CoursesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener lista de cursos con filtros opcionales
     * Listar cursos
     */
    async coursesGetRaw(requestParameters: CoursesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Course>>> {
        const requestOptions = await this.coursesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CourseFromJSON));
    }

    /**
     * Obtener lista de cursos con filtros opcionales
     * Listar cursos
     */
    async coursesGet(requestParameters: CoursesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Course>> {
        const response = await this.coursesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coursesIdDelete without sending the request
     */
    async coursesIdDeleteRequestOpts(requestParameters: CoursesIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling coursesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Eliminar un curso (soft delete)
     * Eliminar curso
     */
    async coursesIdDeleteRaw(requestParameters: CoursesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.coursesIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Eliminar un curso (soft delete)
     * Eliminar curso
     */
    async coursesIdDelete(requestParameters: CoursesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.coursesIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for coursesIdGet without sending the request
     */
    async coursesIdGetRequestOpts(requestParameters: CoursesIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling coursesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener información completa de un curso
     * Obtener detalles del curso
     */
    async coursesIdGetRaw(requestParameters: CoursesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Course>> {
        const requestOptions = await this.coursesIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseFromJSON(jsonValue));
    }

    /**
     * Obtener información completa de un curso
     * Obtener detalles del curso
     */
    async coursesIdGet(requestParameters: CoursesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Course> {
        const response = await this.coursesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coursesIdPut without sending the request
     */
    async coursesIdPutRequestOpts(requestParameters: CoursesIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling coursesIdPut().'
            );
        }

        if (requestParameters['course'] == null) {
            throw new runtime.RequiredError(
                'course',
                'Required parameter "course" was null or undefined when calling coursesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CourseToJSON(requestParameters['course']),
        };
    }

    /**
     * Actualizar información de un curso
     * Actualizar curso
     */
    async coursesIdPutRaw(requestParameters: CoursesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Course>> {
        const requestOptions = await this.coursesIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseFromJSON(jsonValue));
    }

    /**
     * Actualizar información de un curso
     * Actualizar curso
     */
    async coursesIdPut(requestParameters: CoursesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Course> {
        const response = await this.coursesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coursesIdSyllabusGet without sending the request
     */
    async coursesIdSyllabusGetRequestOpts(requestParameters: CoursesIdSyllabusGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling coursesIdSyllabusGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/syllabus`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener el temario completo del curso
     * Obtener temario del curso
     */
    async coursesIdSyllabusGetRaw(requestParameters: CoursesIdSyllabusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Syllabus>>> {
        const requestOptions = await this.coursesIdSyllabusGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SyllabusFromJSON));
    }

    /**
     * Obtener el temario completo del curso
     * Obtener temario del curso
     */
    async coursesIdSyllabusGet(requestParameters: CoursesIdSyllabusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Syllabus>> {
        const response = await this.coursesIdSyllabusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coursesPost without sending the request
     */
    async coursesPostRequestOpts(requestParameters: CoursesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['course'] == null) {
            throw new runtime.RequiredError(
                'course',
                'Required parameter "course" was null or undefined when calling coursesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CourseToJSON(requestParameters['course']),
        };
    }

    /**
     * Crear un nuevo curso (requiere rol TEACHER o ADMIN)
     * Crear curso
     */
    async coursesPostRaw(requestParameters: CoursesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Course>> {
        const requestOptions = await this.coursesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseFromJSON(jsonValue));
    }

    /**
     * Crear un nuevo curso (requiere rol TEACHER o ADMIN)
     * Crear curso
     */
    async coursesPost(requestParameters: CoursesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Course> {
        const response = await this.coursesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
