/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Course,
  CourseLevel,
  CourseStatus,
  EnrolledCourse,
  ErrorResponse,
  Notification,
  Review,
  StudentStats,
} from '../models/index';
import {
    CourseFromJSON,
    CourseToJSON,
    CourseLevelFromJSON,
    CourseLevelToJSON,
    CourseStatusFromJSON,
    CourseStatusToJSON,
    EnrolledCourseFromJSON,
    EnrolledCourseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    NotificationFromJSON,
    NotificationToJSON,
    ReviewFromJSON,
    ReviewToJSON,
    StudentStatsFromJSON,
    StudentStatsToJSON,
} from '../models/index';

export interface CoursesIdEnrollPostRequest {
    id: string;
}

export interface CoursesIdEnrolledGetRequest {
    id: string;
}

export interface CoursesIdReviewsPostRequest {
    id: string;
    review: Review;
}

export interface StudentCatalogGetRequest {
    category?: string;
    level?: CourseLevel;
    status?: CourseStatus;
}

export interface StudentNotificationsGetRequest {
    unreadOnly?: boolean;
}

export interface StudentNotificationsIdReadPutRequest {
    id: string;
}

/**
 * 
 */
export class EstudianteApi extends runtime.BaseAPI {

    /**
     * Creates request options for coursesIdEnrollPost without sending the request
     */
    async coursesIdEnrollPostRequestOpts(requestParameters: CoursesIdEnrollPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling coursesIdEnrollPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/enroll`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Inscribir al estudiante autenticado en un curso
     * Inscribirse en un curso
     */
    async coursesIdEnrollPostRaw(requestParameters: CoursesIdEnrollPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnrolledCourse>> {
        const requestOptions = await this.coursesIdEnrollPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnrolledCourseFromJSON(jsonValue));
    }

    /**
     * Inscribir al estudiante autenticado en un curso
     * Inscribirse en un curso
     */
    async coursesIdEnrollPost(requestParameters: CoursesIdEnrollPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnrolledCourse> {
        const response = await this.coursesIdEnrollPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coursesIdEnrolledGet without sending the request
     */
    async coursesIdEnrolledGetRequestOpts(requestParameters: CoursesIdEnrolledGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling coursesIdEnrolledGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/enrolled`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Verifica si el estudiante autenticado está inscrito en un curso
     * Verificar inscripción en un curso
     */
    async coursesIdEnrolledGetRaw(requestParameters: CoursesIdEnrolledGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        const requestOptions = await this.coursesIdEnrolledGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Verifica si el estudiante autenticado está inscrito en un curso
     * Verificar inscripción en un curso
     */
    async coursesIdEnrolledGet(requestParameters: CoursesIdEnrolledGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.coursesIdEnrolledGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coursesIdReviewsPost without sending the request
     */
    async coursesIdReviewsPostRequestOpts(requestParameters: CoursesIdReviewsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling coursesIdReviewsPost().'
            );
        }

        if (requestParameters['review'] == null) {
            throw new runtime.RequiredError(
                'review',
                'Required parameter "review" was null or undefined when calling coursesIdReviewsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/courses/{id}/reviews`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReviewToJSON(requestParameters['review']),
        };
    }

    /**
     * Crear una nueva reseña para un curso en el que el estudiante está inscrito
     * Valorar un curso
     */
    async coursesIdReviewsPostRaw(requestParameters: CoursesIdReviewsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Review>> {
        const requestOptions = await this.coursesIdReviewsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReviewFromJSON(jsonValue));
    }

    /**
     * Crear una nueva reseña para un curso en el que el estudiante está inscrito
     * Valorar un curso
     */
    async coursesIdReviewsPost(requestParameters: CoursesIdReviewsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Review> {
        const response = await this.coursesIdReviewsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for studentCatalogGet without sending the request
     */
    async studentCatalogGetRequestOpts(requestParameters: StudentCatalogGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/student/catalog`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener el catálogo completo de cursos disponibles en la plataforma para el estudiante autenticado. Admite filtros opcionales por categoría, nivel y estado de publicación.
     * Catálogo de cursos para estudiantes
     */
    async studentCatalogGetRaw(requestParameters: StudentCatalogGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Course>>> {
        const requestOptions = await this.studentCatalogGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CourseFromJSON));
    }

    /**
     * Obtener el catálogo completo de cursos disponibles en la plataforma para el estudiante autenticado. Admite filtros opcionales por categoría, nivel y estado de publicación.
     * Catálogo de cursos para estudiantes
     */
    async studentCatalogGet(requestParameters: StudentCatalogGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Course>> {
        const response = await this.studentCatalogGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for studentEnrollmentsGet without sending the request
     */
    async studentEnrollmentsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/student/enrollments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener lista de cursos en los que está inscrito el estudiante
     * Obtener mis inscripciones
     */
    async studentEnrollmentsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EnrolledCourse>>> {
        const requestOptions = await this.studentEnrollmentsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EnrolledCourseFromJSON));
    }

    /**
     * Obtener lista de cursos en los que está inscrito el estudiante
     * Obtener mis inscripciones
     */
    async studentEnrollmentsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EnrolledCourse>> {
        const response = await this.studentEnrollmentsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for studentNotificationsGet without sending the request
     */
    async studentNotificationsGetRequestOpts(requestParameters: StudentNotificationsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['unreadOnly'] != null) {
            queryParameters['unreadOnly'] = requestParameters['unreadOnly'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/student/notifications`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener lista de notificaciones del estudiante
     * Obtener notificaciones
     */
    async studentNotificationsGetRaw(requestParameters: StudentNotificationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Notification>>> {
        const requestOptions = await this.studentNotificationsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NotificationFromJSON));
    }

    /**
     * Obtener lista de notificaciones del estudiante
     * Obtener notificaciones
     */
    async studentNotificationsGet(requestParameters: StudentNotificationsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Notification>> {
        const response = await this.studentNotificationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for studentNotificationsIdReadPut without sending the request
     */
    async studentNotificationsIdReadPutRequestOpts(requestParameters: StudentNotificationsIdReadPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling studentNotificationsIdReadPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/student/notifications/{id}/read`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Marcar una notificación específica como leída
     * Marcar notificación como leída
     */
    async studentNotificationsIdReadPutRaw(requestParameters: StudentNotificationsIdReadPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.studentNotificationsIdReadPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Marcar una notificación específica como leída
     * Marcar notificación como leída
     */
    async studentNotificationsIdReadPut(requestParameters: StudentNotificationsIdReadPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.studentNotificationsIdReadPutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for studentStatsGet without sending the request
     */
    async studentStatsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/student/stats`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener estadísticas de aprendizaje del estudiante autenticado
     * Obtener estadísticas del estudiante
     */
    async studentStatsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentStats>> {
        const requestOptions = await this.studentStatsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentStatsFromJSON(jsonValue));
    }

    /**
     * Obtener estadísticas de aprendizaje del estudiante autenticado
     * Obtener estadísticas del estudiante
     */
    async studentStatsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentStats> {
        const response = await this.studentStatsGetRaw(initOverrides);
        return await response.value();
    }

}
