/* tslint:disable */
/* eslint-disable */
/**
 * API de GrowUp
 * Especificación de la API para la plataforma de e-learning GrowUp.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Activity,
  AnalyticsSummary,
  CourseItem,
  CoursePerformance,
  DashboardStats,
  RevenueData,
  Review,
} from '../models/index';
import {
    ActivityFromJSON,
    ActivityToJSON,
    AnalyticsSummaryFromJSON,
    AnalyticsSummaryToJSON,
    CourseItemFromJSON,
    CourseItemToJSON,
    CoursePerformanceFromJSON,
    CoursePerformanceToJSON,
    DashboardStatsFromJSON,
    DashboardStatsToJSON,
    RevenueDataFromJSON,
    RevenueDataToJSON,
    ReviewFromJSON,
    ReviewToJSON,
} from '../models/index';

export interface TeacherActivitiesGetRequest {
    limit?: number;
}

export interface TeacherAnalyticsRevenueGetRequest {
    months?: number;
}

/**
 * 
 */
export class ProfesorApi extends runtime.BaseAPI {

    /**
     * Creates request options for teacherActivitiesGet without sending the request
     */
    async teacherActivitiesGetRequestOpts(requestParameters: TeacherActivitiesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teacher/activities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener lista de actividades recientes en los cursos del profesor
     * Obtener actividades recientes
     */
    async teacherActivitiesGetRaw(requestParameters: TeacherActivitiesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Activity>>> {
        const requestOptions = await this.teacherActivitiesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ActivityFromJSON));
    }

    /**
     * Obtener lista de actividades recientes en los cursos del profesor
     * Obtener actividades recientes
     */
    async teacherActivitiesGet(requestParameters: TeacherActivitiesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Activity>> {
        const response = await this.teacherActivitiesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teacherAnalyticsCoursesGet without sending the request
     */
    async teacherAnalyticsCoursesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teacher/analytics/courses`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener análisis de rendimiento de los cursos del profesor
     * Obtener rendimiento de cursos
     */
    async teacherAnalyticsCoursesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CoursePerformance>>> {
        const requestOptions = await this.teacherAnalyticsCoursesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CoursePerformanceFromJSON));
    }

    /**
     * Obtener análisis de rendimiento de los cursos del profesor
     * Obtener rendimiento de cursos
     */
    async teacherAnalyticsCoursesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CoursePerformance>> {
        const response = await this.teacherAnalyticsCoursesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teacherAnalyticsRevenueGet without sending the request
     */
    async teacherAnalyticsRevenueGetRequestOpts(requestParameters: TeacherAnalyticsRevenueGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['months'] != null) {
            queryParameters['months'] = requestParameters['months'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teacher/analytics/revenue`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener datos de ingresos mensuales del profesor
     * Obtener análisis de ingresos
     */
    async teacherAnalyticsRevenueGetRaw(requestParameters: TeacherAnalyticsRevenueGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RevenueData>>> {
        const requestOptions = await this.teacherAnalyticsRevenueGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RevenueDataFromJSON));
    }

    /**
     * Obtener datos de ingresos mensuales del profesor
     * Obtener análisis de ingresos
     */
    async teacherAnalyticsRevenueGet(requestParameters: TeacherAnalyticsRevenueGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RevenueData>> {
        const response = await this.teacherAnalyticsRevenueGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teacherAnalyticsSummaryGet without sending the request
     */
    async teacherAnalyticsSummaryGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teacher/analytics/summary`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener resumen global de analíticas del profesor
     * Obtener resumen de analíticas
     */
    async teacherAnalyticsSummaryGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalyticsSummary>> {
        const requestOptions = await this.teacherAnalyticsSummaryGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalyticsSummaryFromJSON(jsonValue));
    }

    /**
     * Obtener resumen global de analíticas del profesor
     * Obtener resumen de analíticas
     */
    async teacherAnalyticsSummaryGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalyticsSummary> {
        const response = await this.teacherAnalyticsSummaryGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teacherCoursesGet without sending the request
     */
    async teacherCoursesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teacher/courses`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener lista de cursos del profesor autenticado con estadísticas
     * Obtener mis cursos
     */
    async teacherCoursesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CourseItem>>> {
        const requestOptions = await this.teacherCoursesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CourseItemFromJSON));
    }

    /**
     * Obtener lista de cursos del profesor autenticado con estadísticas
     * Obtener mis cursos
     */
    async teacherCoursesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CourseItem>> {
        const response = await this.teacherCoursesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teacherDashboardStatsGet without sending the request
     */
    async teacherDashboardStatsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teacher/dashboard/stats`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener resumen de estadísticas para el panel del profesor
     * Obtener estadísticas del panel
     */
    async teacherDashboardStatsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DashboardStats>> {
        const requestOptions = await this.teacherDashboardStatsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DashboardStatsFromJSON(jsonValue));
    }

    /**
     * Obtener resumen de estadísticas para el panel del profesor
     * Obtener estadísticas del panel
     */
    async teacherDashboardStatsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DashboardStats> {
        const response = await this.teacherDashboardStatsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teacherReviewsGet without sending the request
     */
    async teacherReviewsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teacher/reviews`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener lista de todas las reseñas dejadas en los cursos del profesor
     * Obtener reseñas de mis cursos
     */
    async teacherReviewsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Review>>> {
        const requestOptions = await this.teacherReviewsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReviewFromJSON));
    }

    /**
     * Obtener lista de todas las reseñas dejadas en los cursos del profesor
     * Obtener reseñas de mis cursos
     */
    async teacherReviewsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Review>> {
        const response = await this.teacherReviewsGetRaw(initOverrides);
        return await response.value();
    }

}
